service:
  name: s3-alert
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}

custom:
  defaultStage: dev
  profiles:
    dev: sandbox-bretwaldow-admin

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
